### ISSUE TITLE
Get error at "Populate database with test data"

### ISSUE THREAD

**Issue by thehatami** [superdesk/web-publisher#578] opened 2018-07-14 07:17 UTC
i installed superdesk. after that, i faced to below error on run `php app/console doctrine:fixtures:load`

`The value "<paragraph(10)> <blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-ra  
  dius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(10  
  0% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align  
  :center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHO  
  kAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEO  
  WDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVL  
  qtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></di  
  v></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BNaM68Cj7kD/" style=" color:#000; font-family:Arial,sans-serif;  
   font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Meet Enzo (right), a  
   #Doogler at our Palo Alto office who loves hosting his pal Olive for campus tours (and striking a few poses).</a></p> <p style=" color:#c9c8cd; font-famil  
  y:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow  
  :ellipsis; white-space:nowrap;">Zdjęcie zamieszczone przez użytkownika Google (@google) <time style=" font-family:Arial,sans-serif; font-size:14px; line-he  
  ight:17px;" datetime="2016-11-29T21:37:32+00:00">29 Lis, 2016 o 1:37 PST</time></p></div></blockquote> <script async defer src="//platform.instagram.com/en  
  _US/embeds.js"></script> <paragraph(10)> <iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook%2Fposts%2F10  
  154597567106729%3A0&width=500" width="500" height="608" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></ifram  
  e> <br><paragraph(10)>" contains an unclosed function.`

how can i fix it?

**Comment by ahilles107** [comment] 2018-07-16 07:14
Duplicate of #572

**Closed** 2018-07-16 07:14 UTC

**Comment by thehatami** [comment] 2018-07-16 09:11
dear @ahilles107 why has no answer for this problem?
